In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df.fuel_efficiency_mpg.max()

41.2

In [8]:
df.horsepower.median()

254.0

In [9]:
df.groupby('horsepower').count().sort_values('model_year', ascending=False)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,vehicle_weight,acceleration,fuel_efficiency_mpg
horsepower,,,,,,,,,,
252.0,174,174,174,174,174,174,174,174,164,174
246.0,168,168,168,168,168,168,168,168,165,168
256.0,168,168,168,168,168,168,168,168,162,168
253.0,165,165,165,165,165,165,165,165,161,165
259.0,165,165,165,165,165,165,165,165,160,165
...,...,...,...,...,...,...,...,...,...,...
320.0,1,1,1,1,1,1,1,1,1,1
322.0,1,1,1,1,1,1,1,1,1,1
327.0,1,1,1,1,1,1,1,1,1,1
328.0,1,1,1,1,1,1,1,1,1,1
330.0,1,1,1,1,1,1,1,1,1,1

In [20]:
most_frequent = df['horsepower'].mode()[0]
most_frequent

np.float64(252.0)

In [21]:
df['horsepower']= df['horsepower'].fillna(most_frequent)

In [22]:
df.horsepower.median()

252.0

In [24]:
X = (df[['vehicle_weight', 'model_year']][df['origin']=='Asia'].head(7).values)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [25]:
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [26]:
XTX = XT@X
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [28]:
w = XTX_inv @ X.T @ y
w.sum()

np.float64(0.3691969690492649)